backend:
  name: git-gateway
  branch: master
media_folder: "images/uploads"
collections:
  - name: "event"
    label: "Event"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Event Link", name: "link", widget: "string"}
  - name: "officer"
    label: "Officer"
    folder: "content/officers"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "UXPA Position", name: "role", widget: "string"}
      - {label: "Current/Recent Job Title", name: "job", widget: "string"}
      - {label: "Profile Picture", name: "avatar", widget: "image"}