backend:
  name: git-gateway
  branch: master

media_folder: "public/uploads" # Media files will be stored in the repo under public/uploads
public_folder: "/uploads" # Folder path where uploaded files will be accessed, relative to the base of the built site

collections:
  - name: "event"
    label: "Event"
    folder: "src/events"
    create: true
    slug: "{{slug}}"
    extension: "json"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string", pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', 'A slug can have no spaces, capital letters, or special characters'], hint: "The post URL (slug cannot have spaces, capital letters, or special characters)"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Time", name: "time", widget: "string", hint: "Format 00:00 AM/PM. Times are in PST."}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Location Address", name: "address", widget: "string", required: false}
      - {label: "Ticket Price", name: "price", widget: "string", default: "Free"}
      - {label: "Event Organizer", name: "organization", widget: "string", default: "UXPA Seattle"}
      - {label: "Event Description", name: "markdown", widget: "markdown"}
      - {label: "Event Excerpt", name: "excerpt", widget: "string", pattern: ['.{0,70}.', "No more than 70 characters."]}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: false}
      - {label: "Event External Link", name: "link", widget: "string", required: false}
      - {label: "External Link Display", name: "linkdisplay", widget: "string", required: false, default: "Click to Learn More"}
  - name: "officer"
    label: "Officer"
    folder: "src/officers"
    create: true
    slug: "{{name}}"
    extension: "json"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "UXPA Position", name: "role", widget: "string"}
      - {label: "Current/Recent Job Title", name: "job", widget: "string"}
      - {label: "Profile Picture", name: "avatar", widget: "image", default: "/uploads/blank-avatar.png"}