backend:
  name: git-gateway
  branch: master

media_folder: "public/uploads" # Media files will be stored in the repo under public/uploads
public_folder: "/uploads" # Folder path where uploaded files will be accessed, relative to the base of the built site

collections:
  - name: "event"
    label: "Event"
    folder: "src/events"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Event External Link", name: "link", widget: "string", required: "false"}
      - {label: "Event Description", name: "markdown", widget: "markdown"}
      - {label: "Event Excerpt", name: "excerpt", widget: "string", pattern: ['.{0,70}.', "No more than 70 characters."]}
  - name: "officer"
    label: "Officer"
    folder: "src/officers"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "UXPA Position", name: "role", widget: "string"}
      - {label: "Current/Recent Job Title", name: "job", widget: "string"}
      - {label: "Profile Picture", name: "avatar", widget: "image", default: "/uploads/blank-avatar.png"}